# Generated by Django 4.0.6 on 2022-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_userdetails_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('CON', 'Console'), ('GAD', 'Gadget'), ('GAM', 'Game'), ('TEL', 'TV'), ('legend', 'legend'), ('superstar', 'superstar'), ('young', 'young'), ('prof', 'prof'), ('quick', 'quick'), ('strong', 'strong')], max_length=20),
        ),
    ]
